//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudAjax2020.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class loginCrudAjax
    {
        public int UserId { get; set; }

        [DisplayName("Nombre de usuario.")]
        [Required(ErrorMessage = "Campo requerido.")]
        public string UserName { get; set; }

        [DataType (DataType.Password) ]
        [Required(ErrorMessage = "Campo requerido.")]
        public string StringPassword { get; set; }

        public string LoginErrorMessage { get; set; }

    }
}
